# Shared Kafka Topics
# Topics used across all integrations

topics:
  ## Core Topics
  - name: "{stack}-integrations-incoming-records"
    partitions: 1
    retention_ms: "259200000"      # 3 days
    retention_bytes: "629145600"   # 600 MB

  - name: "{stack}-integrations-errors"
    partitions: 1
    retention_ms: "259200000"      # 3 days
    retention_bytes: "629145600"   # 600 MB

  ## Dead Letter Queues
  - name: "{stack}-integrations-incoming-records-dlq"
    partitions: 1
    retention_ms: "86400000"       # 1 day
    retention_bytes: "209715200"   # 200 MB

  - name: "{stack}-integrations-errors-dlq"
    partitions: 1
    retention_ms: "86400000"       # 1 day
    retention_bytes: "209715200"   # 200 MB
